const text = [
  `"I'm not here to be perfect, I'm here to be real." - Lady Gaga`,
  `"I'm not interested in money. I just want to be wonderful." - Marilyn Monroe`,
  `"The only thing that feels better than winning is winning when nobody thought you could." - Hank Aaron`,
  `"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill`,
  `"If you can dream it, you can do it." - Walt Disney`,
  `"If you want something done, ask a busy person to do it." - Laura Ingalls Wilder`,
  `"If your actions inspire others to dream more, learn more, do more and become more, you are a leader." - John Quincy Adams`,
  `"The best way to find out if you can trust somebody is to trust them." - Ernest Hemingway`,
  `"The only Limit to our realization of tomorrow will be our doubts of today." - Franklin D. Roosevelt`,
  `"We may encounter many defeats but we must not be defeated." - Maya Angelou`,
  `"The most important thing is to enjoy your life - to be happy - it's all that matters." - Steve Jobs`,
  `"The best way to find out what you want in life is to try a lot of things." - Oprah Winfrey`,
  `"Don't let anyone tell you what you can't do. Follow your dreams and persist." - Barack Obama`,
  `"You only live once, but if you do it right, once is enough." - Mae West`,
  `"Life is what we make it and how we make it – whether we realize it or not." - Napoleon Hill`,
  `"I'm not a self-made man. I've had a lot of help." - Stan Lee`,
  `"If you don't build your dream, someone else will hire you to help them build theirs." -Tony Gaskins`,
  `"You've got to be in it to win it." -Tony Robbins`,
  `"Success is stumbling from failure to failure with no loss of enthusiasm." -Winston Churchill`,
  `"People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily." -Zig Ziglar`,
  `"If you want to make your dreams come true, the first thing you have to do is wake up." -J.M. Power`,
  `"The only limit to our realization of tomorrow will be our doubts of today." -Franklin D. Roosevelt`,
  `"We may encounter many defeats but we must not be defeated." -Maya Angelou`,
  `"Be persistent and never give up hope." -George Lucas`,
  `"The best way to find out if you can trust somebody is to trust them." - Ernest Hemingway`,
  `"If you can't handle me at my worst, then you sure as hell don't deserve me at my best." - Marilyn Monroe`,
  `"I can't change the direction of the wind, but I can adjust my sails to always reach my destination." - Jimmy Dean`,
  `"I can accept failure, everyone fails at something. But I can't accept not trying." - Michael Jordan`,
  `"The greatest glory in living lies not in never falling, but in rising every time we fall." - Nelson Mandela`,
  `"The way to get started is to quit talking and begin doing." - Walt Disney`,
  `"I have a dream." - Martin Luther King Jr.`,
];
export default text;
